package com.inyu.dal.master;


import com.inyu.entity.CrmConfig;

import java.util.List;


public interface CrmConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_config
     *
     * @mbg.generated
     */
    int insert(CrmConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_config
     *
     * @mbg.generated
     */
    CrmConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_config
     *
     * @mbg.generated
     */
    List<CrmConfig> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CrmConfig record);
}