package com.inyu.dal.master;

import com.github.pagehelper.Page;
import com.inyu.entity.CrmCustomer;

import java.util.List;
import java.util.Map;

public interface CrmCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer
     *
     * @mbg.generated
     */
    int insert(CrmCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer
     *
     * @mbg.generated
     */
    CrmCustomer selectByPrimaryKey(Integer customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer
     *
     * @mbg.generated
     */
    Page<CrmCustomer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CrmCustomer record);

    /**
     * t通过公司名查询
     * @param params
     * @return
     */
    List<CrmCustomer> queryCustomerInfoByIndustry(Map  params);

    /**
     * 分页查询-count
     * @param params
     * @return
     */
    int countSelectCustomerByPage(Map  params);

    /**
     * 分页查询-by name
     * @param pageParams
     * @return
     */
    List<CrmCustomer> selectCustomerByPage(Map pageParams);
}