package com.inyu.dal.master;

import com.inyu.entity.CrmCustomer;

import java.util.List;

public interface CrmCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer
     *
     * @mbg.generated
     */
    int insert(CrmCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer
     *
     * @mbg.generated
     */
    CrmCustomer selectByPrimaryKey(Integer customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer
     *
     * @mbg.generated
     */
    List<CrmCustomer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CrmCustomer record);

    CrmCustomer queryCustomerInfoByIndustry(String industry);
}