package com.inyu.dal.master;

import com.inyu.entity.QuartzProxy;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

@Mapper
public interface QuartzProxyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_proxy
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_proxy
     *
     * @mbg.generated
     */
    int insert(QuartzProxy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_proxy
     *
     * @mbg.generated
     */
    QuartzProxy selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_proxy
     *
     * @mbg.generated
     */
    List<QuartzProxy> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_proxy
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QuartzProxy record);

    QuartzProxy queryProxyByIp(Map map);

    List<QuartzProxy> selectProxyListByStatus(Map map);
}