package com.inyu.dal.master;

import com.inyu.entity.SysCaptcha;
import java.util.List;

public interface SysCaptchaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_captcha
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_captcha
     *
     * @mbg.generated
     */
    int insert(SysCaptcha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_captcha
     *
     * @mbg.generated
     */
    SysCaptcha selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_captcha
     *
     * @mbg.generated
     */
    List<SysCaptcha> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_captcha
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysCaptcha record);

    SysCaptcha selectByUid(String uuid);

    int deleteByUid(String uuid);
}