package com.inyu.entity;

import java.io.Serializable;
import java.util.Date;

public class CrmUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.salt
     *
     * @mbg.generated
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.telephone
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.reg_ip
     *
     * @mbg.generated
     */
    private String regIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.reg_time
     *
     * @mbg.generated
     */
    private Date regTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.last_login_time
     *
     * @mbg.generated
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.lostpw_time
     *
     * @mbg.generated
     */
    private Date lostpwTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.weixinid
     *
     * @mbg.generated
     */
    private String weixinid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_user.dashboard
     *
     * @mbg.generated
     */
    private String dashboard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crm_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.user_id
     *
     * @return the value of crm_user.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.user_id
     *
     * @param userId the value for crm_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.role_id
     *
     * @return the value of crm_user.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.role_id
     *
     * @param roleId the value for crm_user.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.category_id
     *
     * @return the value of crm_user.category_id
     *
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.category_id
     *
     * @param categoryId the value for crm_user.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.status
     *
     * @return the value of crm_user.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.status
     *
     * @param status the value for crm_user.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.name
     *
     * @return the value of crm_user.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.name
     *
     * @param name the value for crm_user.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.password
     *
     * @return the value of crm_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.password
     *
     * @param password the value for crm_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.nickname
     *
     * @return the value of crm_user.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.nickname
     *
     * @param nickname the value for crm_user.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.salt
     *
     * @return the value of crm_user.salt
     *
     * @mbg.generated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.salt
     *
     * @param salt the value for crm_user.salt
     *
     * @mbg.generated
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.sex
     *
     * @return the value of crm_user.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.sex
     *
     * @param sex the value for crm_user.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.email
     *
     * @return the value of crm_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.email
     *
     * @param email the value for crm_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.telephone
     *
     * @return the value of crm_user.telephone
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.telephone
     *
     * @param telephone the value for crm_user.telephone
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.address
     *
     * @return the value of crm_user.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.address
     *
     * @param address the value for crm_user.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.birthday
     *
     * @return the value of crm_user.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.birthday
     *
     * @param birthday the value for crm_user.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.reg_ip
     *
     * @return the value of crm_user.reg_ip
     *
     * @mbg.generated
     */
    public String getRegIp() {
        return regIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.reg_ip
     *
     * @param regIp the value for crm_user.reg_ip
     *
     * @mbg.generated
     */
    public void setRegIp(String regIp) {
        this.regIp = regIp == null ? null : regIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.reg_time
     *
     * @return the value of crm_user.reg_time
     *
     * @mbg.generated
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.reg_time
     *
     * @param regTime the value for crm_user.reg_time
     *
     * @mbg.generated
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.last_login_time
     *
     * @return the value of crm_user.last_login_time
     *
     * @mbg.generated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.last_login_time
     *
     * @param lastLoginTime the value for crm_user.last_login_time
     *
     * @mbg.generated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.lostpw_time
     *
     * @return the value of crm_user.lostpw_time
     *
     * @mbg.generated
     */
    public Date getLostpwTime() {
        return lostpwTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.lostpw_time
     *
     * @param lostpwTime the value for crm_user.lostpw_time
     *
     * @mbg.generated
     */
    public void setLostpwTime(Date lostpwTime) {
        this.lostpwTime = lostpwTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.weixinid
     *
     * @return the value of crm_user.weixinid
     *
     * @mbg.generated
     */
    public String getWeixinid() {
        return weixinid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.weixinid
     *
     * @param weixinid the value for crm_user.weixinid
     *
     * @mbg.generated
     */
    public void setWeixinid(String weixinid) {
        this.weixinid = weixinid == null ? null : weixinid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_user.dashboard
     *
     * @return the value of crm_user.dashboard
     *
     * @mbg.generated
     */
    public String getDashboard() {
        return dashboard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_user.dashboard
     *
     * @param dashboard the value for crm_user.dashboard
     *
     * @mbg.generated
     */
    public void setDashboard(String dashboard) {
        this.dashboard = dashboard == null ? null : dashboard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", roleId=").append(roleId);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", status=").append(status);
        sb.append(", name=").append(name);
        sb.append(", password=").append(password);
        sb.append(", nickname=").append(nickname);
        sb.append(", salt=").append(salt);
        sb.append(", sex=").append(sex);
        sb.append(", email=").append(email);
        sb.append(", telephone=").append(telephone);
        sb.append(", address=").append(address);
        sb.append(", birthday=").append(birthday);
        sb.append(", regIp=").append(regIp);
        sb.append(", regTime=").append(regTime);
        sb.append(", lastLoginTime=").append(lastLoginTime);
        sb.append(", lostpwTime=").append(lostpwTime);
        sb.append(", weixinid=").append(weixinid);
        sb.append(", dashboard=").append(dashboard);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}