package com.inyu.entity;

import java.io.Serializable;

public class QuartzConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_config.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_config.group
     *
     * @mbg.generated
     */
    private String group;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_config.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_config.cron
     *
     * @mbg.generated
     */
    private String cron;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_config.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_config.msg
     *
     * @mbg.generated
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_config.quartz_class
     *
     * @mbg.generated
     */
    private String quartzClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table quartz_config
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_config.id
     *
     * @return the value of quartz_config.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_config.id
     *
     * @param id the value for quartz_config.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_config.group
     *
     * @return the value of quartz_config.group
     *
     * @mbg.generated
     */
    public String getGroup() {
        return group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_config.group
     *
     * @param group the value for quartz_config.group
     *
     * @mbg.generated
     */
    public void setGroup(String group) {
        this.group = group == null ? null : group.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_config.name
     *
     * @return the value of quartz_config.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_config.name
     *
     * @param name the value for quartz_config.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_config.cron
     *
     * @return the value of quartz_config.cron
     *
     * @mbg.generated
     */
    public String getCron() {
        return cron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_config.cron
     *
     * @param cron the value for quartz_config.cron
     *
     * @mbg.generated
     */
    public void setCron(String cron) {
        this.cron = cron == null ? null : cron.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_config.status
     *
     * @return the value of quartz_config.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_config.status
     *
     * @param status the value for quartz_config.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_config.msg
     *
     * @return the value of quartz_config.msg
     *
     * @mbg.generated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_config.msg
     *
     * @param msg the value for quartz_config.msg
     *
     * @mbg.generated
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_config.quartz_class
     *
     * @return the value of quartz_config.quartz_class
     *
     * @mbg.generated
     */
    public String getQuartzClass() {
        return quartzClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_config.quartz_class
     *
     * @param quartzClass the value for quartz_config.quartz_class
     *
     * @mbg.generated
     */
    public void setQuartzClass(String quartzClass) {
        this.quartzClass = quartzClass == null ? null : quartzClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_config
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", group=").append(group);
        sb.append(", name=").append(name);
        sb.append(", cron=").append(cron);
        sb.append(", status=").append(status);
        sb.append(", msg=").append(msg);
        sb.append(", quartzClass=").append(quartzClass);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}