package com.inyu.entity;

import java.io.Serializable;
import java.util.Date;

public class SysCaptcha implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_captcha.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_captcha.uuid
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_captcha.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_captcha.gmt_last_update
     *
     * @mbg.generated
     */
    private Date gmtLastUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_captcha.gmt_expire
     *
     * @mbg.generated
     */
    private Date gmtExpire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_captcha
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_captcha.id
     *
     * @return the value of sys_captcha.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_captcha.id
     *
     * @param id the value for sys_captcha.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_captcha.uuid
     *
     * @return the value of sys_captcha.uuid
     *
     * @mbg.generated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_captcha.uuid
     *
     * @param uuid the value for sys_captcha.uuid
     *
     * @mbg.generated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_captcha.code
     *
     * @return the value of sys_captcha.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_captcha.code
     *
     * @param code the value for sys_captcha.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_captcha.gmt_last_update
     *
     * @return the value of sys_captcha.gmt_last_update
     *
     * @mbg.generated
     */
    public Date getGmtLastUpdate() {
        return gmtLastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_captcha.gmt_last_update
     *
     * @param gmtLastUpdate the value for sys_captcha.gmt_last_update
     *
     * @mbg.generated
     */
    public void setGmtLastUpdate(Date gmtLastUpdate) {
        this.gmtLastUpdate = gmtLastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_captcha.gmt_expire
     *
     * @return the value of sys_captcha.gmt_expire
     *
     * @mbg.generated
     */
    public Date getGmtExpire() {
        return gmtExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_captcha.gmt_expire
     *
     * @param gmtExpire the value for sys_captcha.gmt_expire
     *
     * @mbg.generated
     */
    public void setGmtExpire(Date gmtExpire) {
        this.gmtExpire = gmtExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_captcha
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uuid=").append(uuid);
        sb.append(", code=").append(code);
        sb.append(", gmtLastUpdate=").append(gmtLastUpdate);
        sb.append(", gmtExpire=").append(gmtExpire);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}